{
    "type": "feature",
    "message": "Workaround bug in Django's schema editor sometimes causing incorrect transaction\nrollbacks resulting in the connection to the database becoming unusable.",
    "issue_number": null,
    "bullet_points": [],
    "created_at": "2023-02-10"
}