{
    "type": "bug",
    "message": "Return proper exception when share_id is invalid",
    "issue_number": 2203,
    "bullet_points": [],
    "created_at": "2023-12-22"
}